//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamAllowOption
    {
        public int Exam_Option_ID { get; set; }
        public string Exam_Allows_Option { get; set; }
        public Nullable<int> Exam_ID { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
