//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamAllowOptions = new HashSet<ExamAllowOption>();
            this.Instructor_Exam_Degree = new HashSet<Instructor_Exam_Degree>();
            this.Student_Result = new HashSet<Student_Result>();
        }
    
        public int Exam_ID { get; set; }
        public string Exam_Type { get; set; }
        public Nullable<int> Exam_Total_Degree { get; set; }
        public Nullable<System.TimeSpan> Exam_Start_Time { get; set; }
        public Nullable<System.TimeSpan> Exam_END_Time { get; set; }
        public Nullable<double> Exam_Total_Time { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
        public Nullable<int> Instructor_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamAllowOption> ExamAllowOptions { get; set; }
        public virtual Instructor Instructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor_Exam_Degree> Instructor_Exam_Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Result> Student_Result { get; set; }
    }
}
