//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor_Exam_Degree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor_Exam_Degree()
        {
            this.Student_Question_Degree = new HashSet<Student_Question_Degree>();
        }
    
        public int Question_Pool_Exam_ID { get; set; }
        public Nullable<int> Instructor_Degree { get; set; }
        public Nullable<int> Question_Pool_ID { get; set; }
        public Nullable<int> Exam_ID { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual QuestionPool QuestionPool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Question_Degree> Student_Question_Degree { get; set; }
    }
}
