//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCQ_Multi_Ans
    {
        public int MCQ_Multi_Ans_ID { get; set; }
        public string MCQ_Multi_Answar { get; set; }
        public Nullable<int> MCQ_ID { get; set; }
    
        public virtual QuestionPool QuestionPool { get; set; }
    }
}
