//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlProjectEntities1 : DbContext
    {
        public SqlProjectEntities1()
            : base("name=SqlProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<ExamAllowOption> ExamAllowOptions { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Instructor_Exam_Degree> Instructor_Exam_Degree { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Intake> Intakes { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MCQ_Multi_Ans> MCQ_Multi_Ans { get; set; }
        public virtual DbSet<MCQuestion> MCQuestions { get; set; }
        public virtual DbSet<QuestionPool> QuestionPools { get; set; }
        public virtual DbSet<Student_Answer> Student_Answer { get; set; }
        public virtual DbSet<Student_Question_Degree> Student_Question_Degree { get; set; }
        public virtual DbSet<Student_Result> Student_Result { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TextQuestion> TextQuestions { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<TrainingManager> TrainingManagers { get; set; }
        public virtual DbSet<TureFalseQuestion> TureFalseQuestions { get; set; }
    }
}
