//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Question_Degree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Question_Degree()
        {
            this.Student_Answer = new HashSet<Student_Answer>();
        }
    
        public int Student_Q_Degree_ID { get; set; }
        public Nullable<int> Student_Question_Degree1 { get; set; }
        public Nullable<int> question_pool_exam_id { get; set; }
    
        public virtual Instructor_Exam_Degree Instructor_Exam_Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Answer> Student_Answer { get; set; }
    }
}
