//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Answer
    {
        public int Student_Ans_ID { get; set; }
        public Nullable<int> Students_ID { get; set; }
        public string Student_Answer1 { get; set; }
        public Nullable<int> Student_Question_Degree_ID { get; set; }
    
        public virtual Student_Question_Degree Student_Question_Degree { get; set; }
        public virtual Student Student { get; set; }
    }
}
