//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextQuestion
    {
        public int Text_Q_ID { get; set; }
        public string Text_Correct_Ans { get; set; }
        public Nullable<int> Question_Poll_ID { get; set; }
    
        public virtual QuestionPool QuestionPool { get; set; }
    }
}
