//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingManager
    {
        public int Training_Mang_ID { get; set; }
        public string Training_Mang_Name { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Login_ID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Login Login { get; set; }
    }
}
